<a href="https://colab.research.google.com/github/SamarthA24/MCA/blob/main/SamarthA_251_LAB7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
'''Create two 3×3 matrices using the random function in Numpy and perform the following operations.
Product (prod)
Multiplication (multiply)
Dot Product (dot)
'''
import numpy as np
import random
matrix1 = np.random.randint(1,10,(3,3))
matrix2 = np.random.randint(1, 10,(3,3))
matrix3 = np.random.randint(2,5)
print("The matrix1 is: ",matrix1)
print("The matrix2 is: ",matrix2)
result1 = np.dot(matrix1, matrix2)
result2 = np.multiply(matrix1, matrix2)
result3 = np.prod(matrix3)
print("The dot product of matrix is: \n",result1)
print("The multiplication of matrix is: \n",result2)
print("The product of matrix is: \n",result3)

The matrix1 is:  [[8 1 5]
 [5 2 8]
 [4 4 8]]
The matrix2 is:  [[4 6 8]
 [1 4 3]
 [6 2 2]]
The dot product of matrix is: 
 [[63 62 77]
 [70 54 62]
 [68 56 60]]
The multiplication of matrix is: 
 [[32  6 40]
 [ 5  8 24]
 [24  8 16]]
The product of matrix is: 
 3


In [9]:
'''Perform the following set operations using the Numpy functions.
Union
Intersection
Set difference
XOR
'''
set1 = np.array([1,2,3,4,5,6])
set2 = np.array([3,4,5,6,7,8])
union_res = np.union1d(set1, set2)
intersection_res = np.intersect1d(set1, set2)
diff_res = np.setdiff1d(set1, set2)
xor_res = np.setxor1d(set1, set2)
print("The union of set is: \n",union_res)
print("The intersection of set is: \n",intersection_res)
print("the difference of the set is: \n",diff_res)
print("the XOR operation of the set is: \n",xor_res)

The union of set is: 
 [1 2 3 4 5 6 7 8]
The intersection of set is: 
 [3 4 5 6]
the difference of the set is: 
 [1 2]
the XOR operation of the set is: 
 [1 2 7 8]


In [19]:
'''Create a 1D array using Random function and perform the following operations.
Cumulative sum
Cumulative Product
Discrete difference (with n=3)
Find the unique elements from the array
'''

a = np.random.randint(1,10,(7))
print(a)
print("The Cumulative Sum of Array is: ", np.cumsum(a))
print("Cumulative Product is: ",np.cumprod(a))
print("The Unique: ",np.unique(a))
print("The Discrete Difference is: ", np.diff(a,n=3))


[9 7 5 5 8 5 2]
The Cumulative Sum of Array is:  [ 9 16 21 26 34 39 41]
Cumulative Product is:  [     9     63    315   1575  12600  63000 126000]
The Unique:  [2 5 7 8 9]
The Discrete Difference is:  [ 2  1 -9  6]


In [20]:
''' Create two 1D array and perform the Addition using zip(), add() and user defined function (frompyfunc())'''

arr = np.array([1, 2, 3, 4, 5])
arr1 = np.array([6, 7, 8, 9, 10])

result_zip = np.array([a + b for a, b in zip(arr, arr1)])

result_np_add = np.add(arr, arr1)

def custom_add(x, y):
    return x + y

ufunc_custom_add = np.frompyfunc(custom_add, 2, 1)
result_custom_add = ufunc_custom_add(arr, arr1)
print("Array 1:", arr)
print("Array 2:", arr1)
print("Addition using zip():", result_zip)
print("Addition using np.add():", result_np_add)
print("Addition using user-defined function:", result_custom_add)

Array 1: [1 2 3 4 5]
Array 2: [ 6  7  8  9 10]
Addition using zip(): [ 7  9 11 13 15]
Addition using np.add(): [ 7  9 11 13 15]
Addition using user-defined function: [7 9 11 13 15]


In [21]:
'''Find the LCM (Least Common Multiple) and GCD (Greatest Common Divisor) of an array of elements using reduce()'''

from functools import reduce
from math import gcd, lcm
elements = [12, 18, 24, 36, 48]

lcm_result = reduce(lambda x, y: lcm(x, y), elements)

gcd_result = reduce(lambda x, y: gcd(x, y), elements)
print("LCM (Least Common Multiple):", lcm_result)
print("GCD (Greatest Common Divisor):", gcd_result)

LCM (Least Common Multiple): 144
GCD (Greatest Common Divisor): 6
